### ISSUE TITLE
Firefox 33.1 之後的版本似乎無法正常運作

### ISSUE THREAD

**Issue by timshan** [racklin/newshelper-firefox#5]
同一則新聞，Firefox上的新聞小幫手毫無反應，但是我用Google Chrome的新聞小幫手卻會提示是問題新聞，不知是否跟Firefox的更新有關？

**Comment by J4X0N** [comment]
47.0.1無效飄過QQ

**Comment by racklin** [comment]
@timshan @J4X0N  Firefox 38 後 addons-sdk 由 cfx -> jpm 且有部份不相容，近年的確都用 chrome , 近日會研究，昇級小幫手版本。
造成不便，請見諒。

**Comment by J4X0N** [comment]
@racklin 真的是太感謝大大了！！！

**Comment by racklin** [comment]
@J4X0N  目前 1.6.1 版本已釋出，已和最新 chrome 版本程式同步。
等待 mozilla review，便會自動更新，或您可以立即自行下載更新。

https://addons.mozilla.org/en-US/firefox/addon/newshelper-firefox/versions/?page=1#version-1.6.1。

**Comment by J4X0N** [comment]
不好意思
今天裝了1.6.2好像還是沒有效果
我有去新聞小幫手測試粉絲頁試過了
沒有訊息跳出QQ
我是47.0.1

**Comment by racklin** [comment]
@J4X0N 謝謝提醒，已修正 fb 處理問題，目前  1.6.3 已上傳審核中，您也可以手動下載測試。
已把此一 issue reopen , 請您再測試看看，造成不便請見諒。
https://addons.mozilla.org/zh-TW/firefox/addon/newshelper-firefox/versions/?page=1#version-1.6.3

**Comment by J4X0N** [comment]
現在好像有運作了
有看到「回報給新聞小幫手」字樣

可是看不到黃色警告
FB沒有警告
新聞也沒有警告

不好意思
麻煩您了QAQ

**Comment by racklin** [comment]
2.0.0 版本使用 WebExtension ，應該可以相容 Firefox 未來版本。
