### ISSUE TITLE
［極需要維護外掛了！］網友回報　安裝之後不成功

### ISSUE THREAD

**Issue by LIMichael** [racklin/newshelper-firefox#6]
如題：極需要維護外掛了！
（本人反應訊息 Firefox 沒有作用／我現在都用 Chrome 版）
（剛剛網友在臉書專頁留言反應，safari 安裝不成功）
（目前只有 Chrome 版是穩定的）
－－－－
我是　Michael_LI　（2013-08-10）第一天就加入新聞小幫手專案　我現在持續管理臉書專頁　以及　編撰回報資料　以及　對外宣傳與合作

目前情況是　臉書公司想跟我們合作（我跟臺灣的媒體觀察基金會在一起執行專案）
2017-03-30（四）　NCC招開：網路訊息事實查核機制分享會　我也參與該會議（g0v的其他人也有參與）
目前政府也很重視這件事情，而且是全球性的議題。

如果可以的的話，外掛請協助改版，讓我們「新聞小幫手」發揮更多影響力。感謝

Michael
2017-04-14
－－－－

**Comment by racklin** [comment]
2.0.0 版本已上線，使用 WebExtension ，應該可以相容 Firefox 未來版本。
