### ISSUE TITLE
webExtension 版本

### ISSUE THREAD

**Issue by wildskyf** [racklin/newshelper-firefox#7]
在 Firefox 57 版後，非 WebExtension 架構的 add-on 會全滅，
我已經把 https://github.com/g0v/newshelper-extension 的版本補正成在 Firefox 上會動的狀態，
（可能有一些 bug，但目前應該堪用）
請 @racklin 協助將 addons.mozilla.org 上的新聞小幫手換成 newshelper-extension 的版本，
若沒辦法的話（我猜 ID 會有問題）請再跟我聯絡，看是我或閣下要重開一個新的。

**Comment by racklin** [comment]
@wildskyf 感謝您的告知，那改的版本方便送個 PR 嗎？

**Comment by wildskyf** [comment]
交給我了

**Comment by racklin** [comment]
@wildskyf 💯

**Comment by wildskyf** [comment]
（雖然我是希望可以直接上 https://github.com/g0v/newshelper-extension 這個 repo 的版本啦ＸＤ）
